### ISSUE TITLE
Unexpected behavior for inputs of format \d+m \d{2,}s

### ISSUE THREAD

**Issue by RafaelMedeirosGomes** [nascjoao/trybe-countdown#8]
### Expected Behaviour

When inputting a value with more than 2 digits for the seconds expected the 'submit' button to be disabled.

### Actual Behaviour

The button is still enabled

### Screenshots 

![window_2021-05-28-12-44-54](https://user-images.githubusercontent.com/62731714/120010430-8537a600-bfb3-11eb-92f3-dfd512147dbc.png)
 
![window_2021-05-28-12-45-07](https://user-images.githubusercontent.com/62731714/120010441-88cb2d00-bfb3-11eb-8af6-c55b437b34e2.png)

**Comment by nascjoao** [comment]
Hello, @RafaelMedeirosGomes! 👋️
Thank you so much for finding a bug!
I will work to fix it as soon as possible.
